#!/bin/sh

xrdb <~/.Xdefaults
xset r rate 200 40
export XAUTHORITY=~/.Xauthority
/usr/bin/xset -b
# set up my mouse button appropriately:
xinput set-button-map $(xinput --list | grep "Evoluent" | sed -e "s/.*id=\([0-9]*\).*/\1/g") 1 2 2 4 5 6 7 3 8

